### ISSUE TITLE
Home Page with Featured Categories

### ISSUE THREAD

**Issue by JillianQuinn** [aibrusci/Seek_Senior_Project#34]
## User Story
As a User I want to see featured categories of activities when I first open the app so that I can get some fast ideas before needing to search/filter myself. Inspires the user to search

## Acceptance Criteria
- [ ] GET request for all activities within a radius and categorize based on filters
- [ ] Featured Categories of Activities 
    - [ ] Categories will have a title header and you will vertically scroll to see more categories
    - [ ] To look at the activities within a category, you will horizontally scroll
- [ ] Activities within a ____ mile radius of the user #14 
- [ ] Seach Bar and filters at the top for the user to then filter #25 #15 
- [ ] Icon to switch to map view #18 
- [ ] Nav bar #33 

## Example
![Home Page(1)](https://user-images.githubusercontent.com/25594364/143727604-39a57eaf-9347-4304-8f46-cbde35059396.png)
