### ISSUE TITLE
Filter Menu

### ISSUE THREAD

**Issue by JillianQuinn** [aibrusci/Seek_Senior_Project#36]
## User Story
As a User I want to see MORE filter options than just the toolbar few options to get more specific. 

## Acceptance Criteria
- [x] GET request for all activities within a radius, and then compile all the relevant filters that those activities have
- [x] Filters should be white with a black outline, but once selected then turn the FB7762 color and with 50% capacity where shaded in #37 
- [x] Selected filters should be at the top of the menu, but otherwise sorted alphabetically
- [x] #15 #35 expands off these filters to show all options
- [x] Clear Filter button removes all selected filters and returns to the home page with featured categories #34
- [x] Apply filters changes which items are displayed must relate to all filters selected #15 

## Example
https://www.figma.com/file/UAVN6f9fgllhOfNG2vdPQD/Seek-Wireframe?node-id=298%3A13226
![Filter Page #2(2)](https://user-images.githubusercontent.com/25594364/143727995-c5a65d8d-cd7c-4e10-8bcb-f9d71c77e15f.png)

// Menu:
width: 375px;
height: 273px;
left: 0px;
top: 0px;
background: #FFFFFF;
border-radius: 15px;
